// AUTO-GENERATED by scripts/sync-openapi.mjs — do not edit by hand.
// Re-run `npm run sync:openapi` to update.

import spec_v9_2_2 from '@/assets/openapi/v9.2.2.yaml?raw'
import spec_v9_2_1 from '@/assets/openapi/v9.2.1.yaml?raw'
import spec_v9_2_0 from '@/assets/openapi/v9.2.0.yaml?raw'
import spec_v9_1_0 from '@/assets/openapi/v9.1.0.yaml?raw'
import spec_v9_0_1 from '@/assets/openapi/v9.0.1.yaml?raw'
import spec_v9_0_0 from '@/assets/openapi/v9.0.0.yaml?raw'
import spec_v8_11_0 from '@/assets/openapi/v8.11.0.yaml?raw'
import spec_v8_10_0 from '@/assets/openapi/v8.10.0.yaml?raw'
import spec_v8_9_0 from '@/assets/openapi/v8.9.0.yaml?raw'
import spec_v8_8_0 from '@/assets/openapi/v8.8.0.yaml?raw'
import spec_v8_7_0 from '@/assets/openapi/v8.7.0.yaml?raw'
import spec_v8_6_0 from '@/assets/openapi/v8.6.0.yaml?raw'
import spec_v8_5_1 from '@/assets/openapi/v8.5.1.yaml?raw'
import spec_v8_5_0 from '@/assets/openapi/v8.5.0.yaml?raw'
import spec_v8_4_0 from '@/assets/openapi/v8.4.0.yaml?raw'
import spec_v8_3_5 from '@/assets/openapi/v8.3.5.yaml?raw'
import spec_v8_3_4 from '@/assets/openapi/v8.3.4.yaml?raw'
import spec_v8_3_3 from '@/assets/openapi/v8.3.3.yaml?raw'
import spec_v8_3_2 from '@/assets/openapi/v8.3.2.yaml?raw'
import spec_v7_11_4 from '@/assets/openapi/v7.11.4.yaml?raw'

/**
 * Map of upstream release tag → raw OpenAPI YAML string.
 * All entries are bundled at build time via Vite ?raw imports.
 */
export const SPEC_VERSIONS: Record<string, string> = {
  'v9.2.2': spec_v9_2_2,
  'v9.2.1': spec_v9_2_1,
  'v9.2.0': spec_v9_2_0,
  'v9.1.0': spec_v9_1_0,
  'v9.0.1': spec_v9_0_1,
  'v9.0.0': spec_v9_0_0,
  'v8.11.0': spec_v8_11_0,
  'v8.10.0': spec_v8_10_0,
  'v8.9.0': spec_v8_9_0,
  'v8.8.0': spec_v8_8_0,
  'v8.7.0': spec_v8_7_0,
  'v8.6.0': spec_v8_6_0,
  'v8.5.1': spec_v8_5_1,
  'v8.5.0': spec_v8_5_0,
  'v8.4.0': spec_v8_4_0,
  'v8.3.5': spec_v8_3_5,
  'v8.3.4': spec_v8_3_4,
  'v8.3.3': spec_v8_3_3,
  'v8.3.2': spec_v8_3_2,
  'v7.11.4': spec_v7_11_4,
}

/** Newest available bundled version. */
export const LATEST_SPEC_TAG = 'v9.2.2'

/** All available version tags in descending order. */
export const SPEC_TAGS = [
  "v9.2.2",
  "v9.2.1",
  "v9.2.0",
  "v9.1.0",
  "v9.0.1",
  "v9.0.0",
  "v8.11.0",
  "v8.10.0",
  "v8.9.0",
  "v8.8.0",
  "v8.7.0",
  "v8.6.0",
  "v8.5.1",
  "v8.5.0",
  "v8.4.0",
  "v8.3.5",
  "v8.3.4",
  "v8.3.3",
  "v8.3.2",
  "v7.11.4"
] as const
